// Generated by npm run classification:types. Edit contracts/classification.schema.json.
// Runtime validation remains required for ranges, formats and semantic invariants.

export type Id = string;

export type Hash = string;

export type Timestamp = string;

export type SchemaVersion = "1.0";

export type ClassificationFacet = "time" | "place" | "person" | "event" | "scene" | "theme" | "content_type" | "quality" | "duplicate";
export const ClassificationFacetValues = ["time","place","person","event","scene","theme","content_type","quality","duplicate"] as const;

export type JobStatus = "pending" | "processing" | "succeeded" | "needs_review" | "failed_retryable" | "failed_terminal" | "cancelled";
export const JobStatusValues = ["pending","processing","succeeded","needs_review","failed_retryable","failed_terminal","cancelled"] as const;

export type ProviderStatus = "succeeded" | "needs_review" | "failed_retryable" | "failed_terminal" | "cancelled";
export const ProviderStatusValues = ["succeeded","needs_review","failed_retryable","failed_terminal","cancelled"] as const;

export type AssertionState = "proposed" | "confirmed" | "edited" | "rejected" | "conflicted" | "withdrawn";
export const AssertionStateValues = ["proposed","confirmed","edited","rejected","conflicted","withdrawn"] as const;

export type LifecycleState = "active" | "trashed" | "deletion_pending" | "deleted";
export const LifecycleStateValues = ["active","trashed","deletion_pending","deleted"] as const;

export type ProviderErrorCode = "TIMEOUT" | "PROVIDER_UNAVAILABLE" | "INVALID_OUTPUT" | "CANCELLED" | "UNSUPPORTED_INPUT" | "INTERNAL_ERROR";
export const ProviderErrorCodeValues = ["TIMEOUT","PROVIDER_UNAVAILABLE","INVALID_OUTPUT","CANCELLED","UNSUPPORTED_INPUT","INTERNAL_ERROR"] as const;

export type SourceType = "visual" | "exif" | "ocr" | "user_text" | "final_asr";
export const SourceTypeValues = ["visual","exif","ocr","user_text","final_asr"] as const;

export type SourceRef = {
  "kind": "object" | "message";
  "id": Id;
};

export type VersionStamp = {
  "schemaVersion": SchemaVersion;
  "algorithmVersion": string;
  "providerVersion": string;
  "modelVersion": string;
  "promptVersion": string;
  "taxonomyVersion": string;
};

export type AsrMetadata = {
  "final": true;
  "producerVersion": string;
  "confidence"?: number;
};

export type Dimensions = {
  "width": number;
  "height": number;
};

export type MinimalAuthorizedEvidenceRef = {
  "evidenceId": Id;
  "sourceRef": SourceRef;
  "sourceHash": Hash;
  "revision": number;
  "byteLength": number;
  "modality": "image";
  "mimeType": "image/jpeg" | "image/png" | "image/webp";
  "dimensions": Dimensions;
} | {
  "evidenceId": Id;
  "sourceRef": SourceRef;
  "sourceHash": Hash;
  "revision": number;
  "byteLength": number;
  "modality": "text";
  "mimeType": "text/plain";
} | {
  "evidenceId": Id;
  "sourceRef": SourceRef;
  "sourceHash": Hash;
  "revision": number;
  "byteLength": number;
  "modality": "transcript";
  "mimeType": "text/plain";
  "asr": AsrMetadata;
};

export type EvidenceRecord = {
  "evidenceId": Id;
  "subjectId": Id;
  "householdId": Id;
  "schemaVersion": SchemaVersion;
  "ownerId": Id;
  "contributorId": Id;
  "circleId"?: Id;
  "consentRef": Id;
  "visibility": "private" | "household" | "circle";
  "visibilityAuthorityRef"?: Id;
  "ingestedAt": Timestamp;
  "capturedAt"?: Timestamp;
  "lifecycleState": "active" | "trashed" | "deletion_pending";
  "sourceRef": SourceRef;
  "sourceHash": Hash;
  "revision": number;
  "byteLength": number;
  "modality": "image";
  "mimeType": "image/jpeg" | "image/png" | "image/webp";
  "dimensions": Dimensions;
} | {
  "evidenceId": Id;
  "subjectId": Id;
  "householdId": Id;
  "schemaVersion": SchemaVersion;
  "ownerId": Id;
  "contributorId": Id;
  "circleId"?: Id;
  "consentRef": Id;
  "visibility": "private" | "household" | "circle";
  "visibilityAuthorityRef"?: Id;
  "ingestedAt": Timestamp;
  "capturedAt"?: Timestamp;
  "lifecycleState": "active" | "trashed" | "deletion_pending";
  "sourceRef": SourceRef;
  "sourceHash": Hash;
  "revision": number;
  "byteLength": number;
  "modality": "text";
  "mimeType": "text/plain";
} | {
  "evidenceId": Id;
  "subjectId": Id;
  "householdId": Id;
  "schemaVersion": SchemaVersion;
  "ownerId": Id;
  "contributorId": Id;
  "circleId"?: Id;
  "consentRef": Id;
  "visibility": "private" | "household" | "circle";
  "visibilityAuthorityRef"?: Id;
  "ingestedAt": Timestamp;
  "capturedAt"?: Timestamp;
  "lifecycleState": "active" | "trashed" | "deletion_pending";
  "sourceRef": SourceRef;
  "sourceHash": Hash;
  "revision": number;
  "byteLength": number;
  "modality": "transcript";
  "mimeType": "text/plain";
  "asr": AsrMetadata;
} | {
  "evidenceId": Id;
  "subjectId": Id;
  "householdId": Id;
  "schemaVersion": SchemaVersion;
  "revision": number;
  "lifecycleState": "deleted";
  "deletedAt": Timestamp;
};

export type ContentBundle = {
  "schemaVersion": SchemaVersion;
  "bundleId": Id;
  "actorId": Id;
  "subjectId": Id;
  "householdId": Id;
  "evidence": Array<EvidenceRecord>;
  "giftScenario"?: "retirement" | "anniversary" | "move_in" | "birthday" | "alumni";
};

export type ProviderConfig = {
  "anonymousClustersEnabled": boolean;
  "biometricConsentRef"?: Id;
  "relevantConfigHash": Hash;
};

export type ClassificationJobRequest = {
  "schemaVersion": SchemaVersion;
  "bundleId": Id;
  "jobId": Id;
  "subjectId": Id;
  "householdId": Id;
  "evidenceIds": Array<Id>;
  "requestedFacets": Array<ClassificationFacet>;
  "versions": VersionStamp;
  "config": ProviderConfig;
  "idempotencyKey": Hash;
};

export type ClassificationJob = {
  "schemaVersion": SchemaVersion;
  "bundleId": Id;
  "jobId": Id;
  "subjectId": Id;
  "householdId": Id;
  "evidenceIds": Array<Id>;
  "requestedFacets": Array<ClassificationFacet>;
  "versions": VersionStamp;
  "config": ProviderConfig;
  "idempotencyKey": Hash;
  "runId": Id;
  "status": JobStatus;
  "attemptCount": number;
  "createdAt": Timestamp;
  "startedAt"?: Timestamp;
  "finishedAt"?: Timestamp;
  "errorCode"?: ProviderErrorCode;
};

export type ClassificationProviderRequest = {
  "schemaVersion": SchemaVersion;
  "runId": Id;
  "jobId": Id;
  "bundleId": Id;
  "subjectId": Id;
  "householdId": Id;
  "idempotencyKey": Hash;
  "inputHash": Hash;
  "versions": VersionStamp;
  "evidence": Array<MinimalAuthorizedEvidenceRef>;
  "requestedFacets": Array<ClassificationFacet>;
  "config": ProviderConfig;
  "deadlineAt": Timestamp;
};

export type Region = {
  "x": number;
  "y": number;
  "width": number;
  "height": number;
};

export type Support = {
  "evidenceId": Id;
  "sourceType": SourceType;
  "producerVersion": string;
  "span"?: {
  "start": number;
  "end": number;
};
  "region"?: Region;
  "weight"?: number;
};

export type LabelValue = {
  "namespace": string;
  "value": string;
};

export type PersonValue = {
  "kind": "text_mention";
  "mention": string;
} | {
  "kind": "face_region";
  "faceRegionId": Id;
  "evidenceId": Id;
  "region": Region;
} | {
  "kind": "person_cluster";
  "personClusterId": Id;
  "faceRegionIds": Array<Id>;
};

export type DuplicateValue = {
  "relation": "exact" | "near";
  "targetEvidenceId": Id;
};

export type ClassificationAssertion = {
  "schemaVersion": SchemaVersion;
  "assertionId": Id;
  "jobId": Id;
  "subjectId": Id;
  "householdId": Id;
  "evidenceRefs": Array<Id>;
  "rawValue": string;
  "confidence": number;
  "supports": Array<Support>;
  "state": AssertionState;
  "sensitivity": "standard" | "sensitive";
  "versions": VersionStamp;
  "inputHash": Hash;
  "revision": number;
  "createdAt": Timestamp;
  "updatedAt": Timestamp;
  "conflictGroupId"?: Id;
  "facet": "time" | "place" | "event" | "scene" | "theme" | "content_type" | "quality";
  "normalizedValue": LabelValue;
} | {
  "schemaVersion": SchemaVersion;
  "assertionId": Id;
  "jobId": Id;
  "subjectId": Id;
  "householdId": Id;
  "evidenceRefs": Array<Id>;
  "rawValue": string;
  "confidence": number;
  "supports": Array<Support>;
  "state": AssertionState;
  "sensitivity": "standard" | "sensitive";
  "versions": VersionStamp;
  "inputHash": Hash;
  "revision": number;
  "createdAt": Timestamp;
  "updatedAt": Timestamp;
  "conflictGroupId"?: Id;
  "facet": "person";
  "normalizedValue": PersonValue;
} | {
  "schemaVersion": SchemaVersion;
  "assertionId": Id;
  "jobId": Id;
  "subjectId": Id;
  "householdId": Id;
  "evidenceRefs": Array<Id>;
  "rawValue": string;
  "confidence": number;
  "supports": Array<Support>;
  "state": AssertionState;
  "sensitivity": "standard" | "sensitive";
  "versions": VersionStamp;
  "inputHash": Hash;
  "revision": number;
  "createdAt": Timestamp;
  "updatedAt": Timestamp;
  "conflictGroupId"?: Id;
  "facet": "duplicate";
  "normalizedValue": DuplicateValue;
};

export type ProviderError = {
  "code": ProviderErrorCode;
};

export type FacetError = {
  "facet": ClassificationFacet;
  "code": ProviderErrorCode;
};

export type Abstention = {
  "facet": ClassificationFacet;
  "reason": "no_assertion" | "insufficient_evidence" | "low_confidence" | "not_applicable";
};

export type ClassificationProviderResult = {
  "schemaVersion": SchemaVersion;
  "runId": Id;
  "jobId": Id;
  "subjectId": Id;
  "householdId": Id;
  "inputHash": Hash;
  "versions": VersionStamp;
  "status": ProviderStatus;
  "assertions": Array<ClassificationAssertion>;
  "facetErrors": Array<FacetError>;
  "abstentions": Array<Abstention>;
  "error"?: ProviderError;
  "usage": {
  "latencyMs": number;
  "inputUnits": number;
  "outputUnits": number;
};
};

export type AssertionReviewRequest = {
  "schemaVersion": SchemaVersion;
  "assertionId": Id;
  "expectedRevision": number;
  "actorId": Id;
  "subjectId": Id;
  "householdId": Id;
  "authorityType": "self" | "explicit_delegate" | "legal_representative";
  "authorityRef": Id;
  "action": "confirm" | "reject" | "withdraw";
} | {
  "schemaVersion": SchemaVersion;
  "assertionId": Id;
  "expectedRevision": number;
  "actorId": Id;
  "subjectId": Id;
  "householdId": Id;
  "authorityType": "self" | "explicit_delegate" | "legal_representative";
  "authorityRef": Id;
  "action": "edit";
  "normalizedValue": LabelValue | PersonValue | DuplicateValue;
};

export interface ContractMap {
  Id: Id;
  Hash: Hash;
  Timestamp: Timestamp;
  SchemaVersion: SchemaVersion;
  ClassificationFacet: ClassificationFacet;
  JobStatus: JobStatus;
  ProviderStatus: ProviderStatus;
  AssertionState: AssertionState;
  LifecycleState: LifecycleState;
  ProviderErrorCode: ProviderErrorCode;
  SourceType: SourceType;
  SourceRef: SourceRef;
  VersionStamp: VersionStamp;
  AsrMetadata: AsrMetadata;
  Dimensions: Dimensions;
  MinimalAuthorizedEvidenceRef: MinimalAuthorizedEvidenceRef;
  EvidenceRecord: EvidenceRecord;
  ContentBundle: ContentBundle;
  ProviderConfig: ProviderConfig;
  ClassificationJobRequest: ClassificationJobRequest;
  ClassificationJob: ClassificationJob;
  ClassificationProviderRequest: ClassificationProviderRequest;
  Region: Region;
  Support: Support;
  LabelValue: LabelValue;
  PersonValue: PersonValue;
  DuplicateValue: DuplicateValue;
  ClassificationAssertion: ClassificationAssertion;
  ProviderError: ProviderError;
  FacetError: FacetError;
  Abstention: Abstention;
  ClassificationProviderResult: ClassificationProviderResult;
  AssertionReviewRequest: AssertionReviewRequest;
}
