import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const schema = JSON.parse(await readFile(new URL('contracts/classification.schema.json', root), 'utf8'));
// A deliberately bounded generator, not a JSON Schema validator.
const allowed = new Set(['$ref', 'type', 'enum', 'const', 'oneOf', 'properties', 'required',
  'additionalProperties', 'items', 'minItems', 'maxItems', 'uniqueItems', 'minimum', 'maximum',
  'minLength', 'maxLength', 'pattern', 'format']);
function typeOf(node) {
  for (const key of Object.keys(node)) {
    if (!allowed.has(key)) throw new Error(`Unsupported schema keyword: ${key}`);
  }
  if (node.$ref) {
    const name = node.$ref.replace('#/definitions/', '');
    if (!schema.definitions[name]) throw new Error('Unknown schema reference');
    return name;
  }
  if ('const' in node) return JSON.stringify(node.const);
  if (node.enum) return node.enum.map(JSON.stringify).join(' | ');
  if (node.oneOf) return node.oneOf.map(typeOf).join(' | ');
  if (node.type === 'object') {
    if (node.additionalProperties !== false) throw new Error('Open object is unsupported');
    return `{\n${Object.entries(node.properties).map(([k, v]) =>
      `  ${JSON.stringify(k)}${node.required.includes(k) ? '' : '?'}: ${typeOf(v)};`).join('\n')}\n}`;
  }
  if (node.type === 'array') return `Array<${typeOf(node.items)}>`;
  if (node.type === 'integer' || node.type === 'number') return 'number';
  if (['string', 'boolean'].includes(node.type)) return node.type;
  throw new Error('Unsupported schema structure');
}
const definitions = Object.entries(schema.definitions);
const output = '// Generated by npm run classification:types. Edit contracts/classification.schema.json.\n' +
  '// Runtime validation remains required for ranges, formats and semantic invariants.\n\n' +
  definitions.map(([name, node]) => `export type ${name} = ${typeOf(node)};\n` +
    (node.enum ? `export const ${name}Values = ${JSON.stringify(node.enum)} as const;\n` : '')).join('\n') +
  '\nexport interface ContractMap {\n' + definitions.map(([name]) => `  ${name}: ${name};`).join('\n') + '\n}\n';
const target = new URL('src/lib/algorithms/classification/types.ts', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Generated classification types are stale');
  console.log('Classification types and enums match JSON Schema.');
} else {
  await writeFile(target, output);
}
